name: compila y genera pdf

on:
  push:

jobs:
  compila:
    runs-on: ubuntu-latest

    steps:
    - name: copialocalCheckout
      uses: actions/checkout@v4.2.2

    - name: local.net
      uses: actions/setup-dotnet@v3.4.2
      with:
        dotnet-version: '9.0.x'

    - name: instalar dependencias
      run: dotnet restore

    - name: compilar
      run: dotnet build --no-restore

  crear-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          images_dir: docs/images
          build_html: false
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
